*  Whiteboard Copy

| 1 | xing qi ji?     | What day of the week is it? |
| 2 | ji yue ji hao   | What date is it?            |
| 3 | yao shi A jiu B | If A then B                 |
| 4 | ke shi          | ... but ...                 |

*  Scratch

  | zheige xingqi | this week |
  | shangge xinqi | last week |
  | xiage xinqi   | next week |

tan - talk about
ji du - wie viele grad?
bu le - gemaessigt

xia xiaoyu leichter regen
xia dayu starker regen

xia xiaoxue leichter schnee
xia daxue starker regen

you yidianr = you yidiar (aussprache) 

wo juede aomen xinqi si de tianqi henhao. jintian shi-ba du hen liangkuai

* Toronto Weather

ke si meng de laojia shi toronto. 

tianqi yubao shuo place time (bu) ...


A he B bu yiyang 

zuo - do / take 
kuai expensive 

shenme bi shenme kuai / was is more expensive?

deduo (much more)
yi dianr (a little bit)

jiejie bi meimei gao yidianr

keqi - nice, kind

geng - even more
xue laoshi bi ... laoshi geng piaoliang

office - gong shi
classroom - jiao shi

shuang - a pair of ... (measure word - NICHT liang ge shuang... )

gaogen xie - high heels
qiu xie

piannyi - cheap
gui - expensive
shufu - comfortable

haochi

daqiu - play ball
hua bing - ice scate

dian nao - computer / electronic brain
shoujie - handy
kuai (fast)

suoyou de (all)

*  The Sentence Final Particle

tianqi nuanhuo le (the weather becomes warm) ; change of state

you kong - have time

yiqian - past
zhi (only)
